title: "NIST Opensource Portal Theme for Jekyll"
author: "Ian Lee <lee1001@llnl.gov>"
description: "Opensource Template"

# Correct linking GitHub Project pages
# Note leading slash in baseurl
githubrepo: Opensource-Theme
baseurl: /Opensource-Theme

permalink: pretty

kramdown:
  auto_ids: true
